title: EEOB/BCB 546X
description: Content for EEOB/BCB 546X - Computational Sills for Biological Data, a graduate-level course taught at Iowa State University.
url: "https://eeob-biodata.github.io/EEOB-BCB-546X"
theme: millidocs

markdown: kramdown
kramdown:
syntax_highlighter_opts:
  disable : true

exclude:
- Gemfile
- Gemfile.lock
- README.md

remote_theme: alexander-heimbuch/millidocs
